defaults: &defaults
  VIDEO_DOWNLOAD_URI: 'http://api.nimbb.com/Video/Download.aspx'
  PUBLIC_KEY: 'b47ef629cb'
  PRIVATE_KEY: '9de83c794f'
  VIDEO_FORMAT: 'flv'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

