cache_verified_twitter_users:
  every: 3hs
  class: CacheVerifiedTwitterUser
  description: 'Fetch and store verified twitter users'

cache_trendspottr_trends:
  every: 1hs
  class: CacheTrendspottrPopularTrends
  description: 'Fetch and store Trendspottr popular topics and searches'

generate_reports:
  cron: '0 0 * * * America/New_York'
  class: GenerateReports
  description: 'Generate provider / out reports and email them.'

